### ISSUE TITLE
Articles.csv seems to be un-used

### ISSUE THREAD

**Issue by MikeHingley22** [toolleeo/awesome-cli-apps-in-a-csv#101]
The makefile seems to suggest  that there should be a data/cli-apps.md - but while this file created, it isn't checked in.  This file uses an `articles.csv` and seems to be mostly links to other sites.

If this data is no longer required, it should probably be deleted,

**Comment by MikeHingley22** [comment]
@toolleeo - I guess the argument might be : 

Someone might make improvements to these files, only for that data to go nowhere - like https://github.com/toolleeo/awesome-cli-apps-in-a-csv/commit/c95092823c6ba703ac03654c289a3b0c02c599a6 -where trademark and acronym fixes were applied to apps.csv, articles.csv and resources.csv : 

The effort involved in patching the articles and resources file were pretty much ineffective, as those changes won't go anywhere, and still only exist in the csv files.  Now in real terms those changes were minimal (updating some cases, grammar etc) - but imagine if someone contributed a number of articles into the articles data file.  That contribution currently would be meaningless because those articles would only exist in that csv file.

**Comment by toolleeo** [comment]
While I understand the argument of being cautious, I note that nowhere in the repo there is any reference to that file or instructions/requests to contribute to that file.
The contribution that you mention was done due to an *automatic* review of all `md` files, which took no effort.

I can understand that, maybe, someone could think about providing contributions to random files in a repository, and nobody can stop if one wish to do that...
